"""
Ship Agent (Phase 1.3)
----------------------
Opens the GitHub PR — but ONLY after the CEO has approved it at pr_gate.
PR creation used to live inside QA, which meant a PR was opened with no human
sign-off. It now runs here, after approval, so nothing is pushed without a gate.

DESIGN DECISION: git add/commit/push + gh pr create in one subprocess call.
BLOCKER: requires a git repo in workspace/ and an authenticated gh CLI.
"""

import subprocess

from graph.state import ProjectState
from tools.file_io import code_root


def run(state: ProjectState) -> dict:
    # Operate on the actual code location: the project/target repo in extend/managed mode,
    # else the greenfield workspace dir.
    pr_url = _open_pr(str(code_root(state)), state["project_id"])
    return {
        "current_node": "ship",
        "pr_url": pr_url,
    }


def _open_pr(project_dir: str, project_id: str) -> str:
    branch = f"feature/{project_id}"

    cmds = [
        f"cd {project_dir}",
        f"git checkout -b {branch} 2>/dev/null || git checkout {branch}",
        "git add -A",
        f'git commit -m "feat({project_id}): generated by agent pipeline"',
        "git push -u origin HEAD",
        f'gh pr create --title "feat: {project_id}" --body "Auto-generated by agent pipeline. QA passed and CEO approved." --head {branch}',
    ]

    result = subprocess.run(
        " && ".join(cmds),
        shell=True,
        capture_output=True,
        text=True,
    )

    if result.returncode == 0:
        for line in result.stdout.splitlines():
            if "github.com" in line:
                return line.strip()
    else:
        print(f"[ship] PR creation failed: {result.stderr[:200]}")

    return "PR creation failed - check gh auth status"
